services:
  aria2-pro:
    image: p3terx/aria2-pro
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - RPC_SECRET=P3TERX
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /mnt/ssd/data/downloads:/downloads
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /mnt/ssd/data/sonarr-config:/config
      - /mnt/ssd/data/downloads:/downloads
      - /mnt/ssd/data/tv:/tv
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /mnt/ssd/data/radarr-config:/config
      - /mnt/ssd/data/downloads:/downloads
      - /mnt/ssd/data/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /mnt/ssd/data/bazarr-config:/config
      - /mnt/ssd/data/tv:/tv
      - /mnt/ssd/data/movies:/movies
      - /mnt/ssd/data/downloads:/downloads
    ports:
      - 6767:6767
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /mnt/ssd/data/prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  aria-ng:
    image: p3terx/ariang
    command: --port 6880
    ports:
      - 6880:6880
    restart: unless-stopped

  copyparty:
    image: copyparty/ac
    ports:
      - 3923:3923
    volumes:
      - /mnt/ssd/data:/w
      - ./copyparty-config:/cfg
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 8191:8191
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "8096:8096/tcp"
      - "7359:7359/udp"
    volumes:
      - /mnt/ssd/data/jellyfin/config:/config
      - /mnt/ssd/data/jellyfin/mdk:/cache
      - /mnt/ssd/data/tv:/media/tv
      - /mnt/ssd/data/movies:/media/movies
    restart: unless-stopped